config/routes.rb
Rails.application.routes.draw do
  get 'home/zipcode'
  root 'home#index'

  post "zipcode" => 'home#zipcode'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/https'
    require 'json'

    @url = 'https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=06504&distance=25&API_KEY=60C5BA67-517D-4D9A-B5AF-4AC171FF59AA'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @output = JSON.parse(@response)

    # Check for empty return result
    if @output.empty?
      @final_output = "Error"

    elsif !@output
      @final_output = "Error"

    else
      @final_output = @output[0]['AQI']
    end

    if @final_output == "Error"
      @api_color = "gray"
      @api_description = "You get no output information this time"
    elsif @final_output <= 50
      @api_color = "green"
      @api_description = "Enjoy your outdoors activitys"
    elsif @final_output >= 51 && @final_output <= 100
      @api_color = "yellow"
      @api_description = "Its safe to be outside"
    elsif @final_output >= 101 && @final_output <= 150
      @api_color = "orange"
      @api_description = "It can be litle harder to breath"
    elsif @final_output >= 151 && @final_output <= 200
      @api_color = "red"
      @api_description = "I would stay inside"
    elsif @final_output >= 201 && @final_output <= 300
      @api_color = "purple"
      @api_description = "Get inside fast"
    elsif @final_output >= 301 && @final_output <= 500
      @api_color = "maroon"
      @api_description = "DANGER DANGER DONT GO OUT SIDE!"
    end
  end

  def zipcode
    @zip_query = params[:zipcode]
    if params[:zipcode] == ""
      @zip_query = "Hey you forgot to enter a zipcode!"
    elsif params[:zipcode]
      require 'net/https'
      require 'json'

      @url = 'https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode='+ @zip_query + '&distance=25&API_KEY=60C5BA67-517D-4D9A-B5AF-4AC171FF59AA'
      @uri = URI(@url)
      @response = Net::HTTP.get(@uri)
      @output = JSON.parse(@response)

      # Check for empty return result
      if @output.empty?
        @final_output = "Error"

      elsif !@output
        @final_output = "Error"

      else
        @final_output = @output[0]['AQI']
      end

      if @final_output == "Error"
        @api_color = "gray"
        @api_description = "You get no output information this time"
      elsif @final_output <= 50
        @api_color = "green"
        @api_description = "Enjoy your outdoors activitys"
      elsif @final_output >= 51 && @final_output <= 100
        @api_color = "yellow"
        @api_description = "Its safe to be outside"
      elsif @final_output >= 101 && @final_output <= 150
        @api_color = "orange"
        @api_description = "It can be litle harder to breath"
      elsif @final_output >= 151 && @final_output <= 200
        @api_color = "red"
        @api_description = "I would stay inside"
      elsif @final_output >= 201 && @final_output <= 300
        @api_color = "purple"
        @api_description = "Get inside fast"
      elsif @final_output >= 301 && @final_output <= 500
        @api_color = "maroon"
        @api_description = "DANGER DANGER DONT GO OUT SIDE!"
      end
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <%= link_to "My Ozone", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>

      <%= form_tag zipcode_path, :method => 'POST' do %>
      <div class="d-flex" role="search">
        <%= text_field_tag 'zipcode', nil, placeholder: "Search Zipcode", class:"form-control me-2" %>
        <%= submit_tag 'Search', class: 'btn btn-outline-primary my-2 my-sm-0' %>
      <% end %>
      </div>

    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4"><%= @final_output %></h1>
  <p class="lead">This is the current ozone air quality in the city of New Haven </p>
  <hr class="my-4">
  <p><%= @api_description %></p>
  <p class="lead">
  </p>
</div>


<br/>

app/views/home/zipcode.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4"><%= @final_output %></h1>
  <p class="lead">This is the current ozone air quality for <%= @zip_query%> zipcode. </p>
  <hr class="my-4">
  <p><%= @api_description %></p>
  <p class="lead">
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ozone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
      <br/>
      <%= yield %>
    </div>
  </body>
</html>